spring:
  application:
    name: sportshop
  r2dbc:
    url: r2dbc:mysql://localhost:3306/sports_shop
    username: root
    password: 0709
    pool:
      enabled: true
      initial.size: 5
      max-size: 20
      max-idle-time: 30m
      max-acquire-time: 10s
      max-create-connection-time: 10s
      validation-query: "SELECT 1 FROM DUAL"
    #logging:
      #level:
        #org.springframework.r2dbc: DEBUG
        #io.r2dbc: DEBUG
